---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

verifier:
  name: inspec

platforms:
  - name: fedora-24

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
